# Set download URL and checksum based on architecture
- name: Set k3s download URL and checksum for x64
  set_fact:
    k3s_download_url: "{{ k3s_binary_url_x64 }}"
    k3s_download_checksum: "{{ k3s_binary_checksum_x64 }}"
  when: ansible_facts.architecture == "x86_64"

- name: Set k3s download URL and checksum for arm64
  set_fact:
    k3s_download_url: "{{ k3s_binary_url_arm64 }}"
    k3s_download_checksum: "{{ k3s_binary_checksum_arm64 }}"
  when:
    - ( ansible_facts.architecture is search("arm") and ansible_facts.userspace_bits == "64" )
      or ansible_facts.architecture is search("aarch64")

- name: Set k3s download URL and checksum for armhf
  set_fact:
    k3s_download_url: "{{ k3s_binary_url_armhf }}"
    k3s_download_checksum: "{{ k3s_binary_checksum_armhf }}"
  when:
    - ansible_facts.architecture is search("arm")
    - ansible_facts.userspace_bits == "32"

# Download the k3s binary using the local URL and checksum
- name: Download k3s binary
  ansible.builtin.get_url:
    url: "{{ k3s_download_url }}"
    checksum: "{{ k3s_download_checksum }}"
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: "0755"
